# Data availability {.appendix}

The results presented here are based on the directory of open archaeology projects maintained at <https://open-archaeo.info> [@batist2023].
The specific version we used is available from Zenodo at <https://doi.org/10.5281/zenodo.10625236> as well as in the compendium associated with this paper [@roe2024, https://doi.org/10.5281/zenodo.8393043], in CSV format under `analysis/raw_data`.

Further data on activity in the git repositories associated with these projects was obtained via the GitHub API.
This data is available from Zenodo in the compendium associated with this paper [@roe2024, <https://doi.org/10.5281/zenodo.8393043>], in RData and CSV format under `analysis/derived_data`.

# Acknowledgements {.appendix}

The impetus for this work was a session at the Computer Applications and Quantitative Methods in Archaeology (CAA) virtual annual meeting in Cyprus in June 2021.
Our thanks to Martin Hinz, Clemens Schmid, Sophie Schmidt and other members of the 'scientific scripting languages in archaeology (CAA-SSLA, <https://sslarch.github.io/>) for organizing the session and encouraging us to develop the work further.

Our original manuscript benefited greatly from the insights of the anonymous reviewer for *Internet Archaeology*.
We are also grateful to *IA* editor Judith Winters for managing the process and facilitating the interactive figures.

JR was supported by the Swiss National Science Foundation (SNSF Project #198152) for the duration of the production of this work.

<!-- TODO: Zack: anything to add? -->
