---
title: Open archaeology, open source?
subtitle: Collaborative practices in an emerging community of archaeological software engineers
author:
  - name: Zachary Batist
    url: https://zackbatist.info
    affiliation: Independent Scholar
    orcid: 0000-0003-0435-508X 
  - name: Joe Roe
    url: https://joeroe.io
    affiliation: Institute of Archaeological Sciences, University of Bern
    affiliation-url: https://www.iaw.unibe.ch/
    orcid: 0000-0002-1011-1244
date: 2024-07-18
abstract: |
  Surveying the first quarter-century of computer applications in archaeology, Scollar [-@scollar1999] lamented that the field relied almost exclusively on "hand-me-down" tools repurposed from other disciplines. Twenty five years later, this is no longer the case: computational archaeologists often find themselves practicing the dual roles of data analyst and research software engineer [@baxter2012; @schmidt2020], developing and applying new tools that are tailored specifically to archaeological problems and archaeological methods. Though this trend can be traced to the very earliest days of the field [@cowgill1967], its most recent manifestation is distinguished by its apparent embrace of practices from free and open source software. Most prominently, since around 2015, there has been a rapid uptake of workflow tools designed for open source development communities, such as the version control system git and associated online source code management platforms (e.g. GitHub, GitLab). These tools facilitate collaboration among developers and users of open source software using patterns that can diverge quite radically from conventional scholarly norms [@tennant2020].

  In this paper, we investigate modes of collaboration in this emerging community of practice using 'open-archaeo', a curated list of archaeological software, and data on the activity of associated GitHub repositories and users.
  We conduct an exploratory quantitative analysis to characterize the nature and intensity of these collaborations and map the collaborative networks that emerge from them.
  We document uneven adoption of open source collaborative practices beyond the basic use of git as a version control system and GitHub to host source code.
  Most projects do make use of collaborative features and, through shared contributions, we can can trace a collaborative network that includes the majority of archaeologists active on GitHub.
  However, a majority of repositories have 1–3 contributors, with only a few projects distinguished by an active and diverse developer base.
  Direct collaboration on code or other repository content—as opposed to the more passive, social media-style interaction that GitHub supports—remains very limited.
  In other words, there is little evidence that archaeologists' adoption of open source *tools* (git and GitHub) has been accompanied by the decentralized, participatory forms of collaboration that characterise other open source communities.
  On the contrary, our results indicate that research software engineering in archaeology remains largely embedded in conventional professional norms and organizational structures of academia.
keywords:
  - open archaeology
  - open source
  - open science
  - archaeological practice
  - collaboration
license: CC BY
citation:
  title: "Open archaeology, open source? Collaborative practices in an emerging community of archaeological software engineers"
  container-title: Internet Archaeology
  volume: 67
  doi: 10.11141/ia.67.13
funding: "Open access funding was provided by the University of Bern and swissuniversities"
bibliography: references.bib
format:
  html:
    page-layout: article
    toc: true
    number-sections: true
    embed-resources: true
execute:
  echo: false
  message: false
  warning: false
---

```{r setup}
options("tinytable_tabularray_placement" = "H")
library("openarchaeoCollaboration") # this package, install with devtools::build()
```

```{r dependencies}
library("english")
library("fs")
library("ggiraph")
library("ggraph")
library("ggpmisc")
library("glue")
library("here")
library("khroma")
library("lubridate")
library("patchwork")
library("rgexf")
library("scales")
library("tidygraph")
library("tidyverse")
library("tinytable")
```

```{r plot-theme}
theme_oarch <- function() {
  theme_minimal() +
  theme()
}
```

{{< include _01-introduction.qmd >}}
{{< include _02-background.qmd >}}
{{< include _03-data_methodology.qmd >}}
{{< include _04-open_archaeology.qmd >}}
{{< include _05-collaboration.qmd >}}
{{< include _06-network.qmd >}}
{{< include _07-conclusion.qmd >}}
{{< include _99-appendices.qmd >}}
